apiVersion: v1
kind: PersistentVolumeClaim
metadata:
        name: pod-pvc
        labels:
                app: php
spec:
        accessModes:
                - ReadWriteMany
        resources:
                requests:
                        storage: 10Gi


