apiVersion: v1
kind: service
metadata:
        name: pod-deployment
        labels:
                app: php-interpreter
        spec:
                ports:
                        - port: 80
                selector:
                        app: php-interpreter
                type: NodePort
